#!/usr/bin/env bash -e

origin="$1"
target="$2"

if [ -z "$origin" ]; then
  echo "Usage: pg copy <origin> <target>"
  exit 1
fi

if [ -z "$target" ]; then
  echo "Usage: pg copy <origin> <target>"
  exit 1
fi

pg-kill-connections "$origin"

psql postgres <<EOF
CREATE DATABASE "$target" WITH TEMPLATE "$origin";
EOF
