#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: pg help [--usage] COMMAND

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help pg
fi

lasher _help pg "$command"
