#!/usr/bin/env bash

set -e

db_name="$1"

if [ -z "$db_name" ]; then
  echo "Usage: pg kill-connections <db_name>"
  exit 1
fi

psql postgres > /dev/null <<EOF
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname='$db_name';
EOF
