#!/usr/bin/env bash -e

db_name="$1"

if [ -z "$db_name" ]; then
  echo "Usage: pg save <db_name>"
  exit 1
fi

pg-kill-connections "$db_name"
pg-drop "snapshot"

psql postgres <<EOF
CREATE DATABASE snapshot WITH TEMPLATE $db_name;
EOF
